export const EXPERIENCES_SET = 'EXPERIENCES_SET'
export const EXPERIENCES_NEW = 'EXPERIENCES_NEW'
export const EXPERIENCES_UPDATE = 'EXPERIENCES_UPDATE'
export const EXPERIENCES_DELETE = 'EXPERIENCES_DELETE'

export const RECENTLIES_SET = 'RECENTLIES_SET'
export const RECENTLIES_NEW = 'RECENTLIES_NEW'
export const RECENTLIES_UPDATE = 'RECENTLIES_UPDATE'
export const RECENTLIES_DELETE = 'RECENTLIES_DELETE'
