export const RECENTLIES_SET = 'RECENTLIES_SET'
export const RECENTLIES_NEW = 'RECENTLIES_NEW'
export const RECENTLIES_UPDATE = 'RECENTLIES_UPDATE'
export const RECENTLIES_DELETE = 'RECENTLIES_DELETE'
